### ISSUE TITLE
Malfunctioning sensors on Asus TUF GAMING A15 (FA506IU)

### ISSUE THREAD

**Issue by antuan1996** [sirlucjan/copr-linux-cachyos#5]
Hi. I got an issue with the battery and fan sensors after switching to the kernel. There is no information about fans at all. The system is showing the same charge level for the battery all the time no matter if I charge or discharge it. I use TLP for battery care and it does not function properly due to the issue. 
I first detected the issue on 6.3 builds.  I’ve done some experimenting and the sensors work fine on:
- Fedora stable kernel;
- Fedora kernel 6.4.3 with TKG patches;
- Vanilla LTS kernel 6.1.35 with Cachyos patches (built with the spec from this repository).

**Comment by sirlucjan** [comment]
It seems that @bieszczaders will help here, unfortunately I don't use Fedora, only Arch Linux.

Connected charger:

```
lucjan at cachyos ~ 20:20:42    
❯ upower -d 
Device: /org/freedesktop/UPower/devices/line_power_AC
  native-path:          AC
  power supply:         yes
  updated:              czw, 20 lip 2023, 08:01:56 (44440 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               Hewlett-Packard
  model:                Primary
  serial:               02241 2018/03/22
  power supply:         yes
  updated:              czw, 20 lip 2023, 20:22:30 (6 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               pending-charge
    warning-level:       none
    energy:              29,4348 Wh
    energy-empty:        0 Wh
    energy-full:         37,563 Wh
    energy-full-design:  46,512 Wh
    energy-rate:         0 W
    voltage:             12,251 V
    charge-cycles:       277
    percentage:          78%
    capacity:            80,7598%
    technology:          lithium-ion
    icon-name:          'battery-full-charging-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              czw, 20 lip 2023, 18:01:53 (8443 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               pending-charge
    warning-level:       none
    energy:              29,4348 Wh
    energy-full:         37,563 Wh
    energy-rate:         0 W
    charge-cycles:       N/A
    percentage:          78%
    icon-name:          'battery-full-charging-symbolic'

Daemon:
  daemon-version:  1.90.2
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: PowerOff
```
Disconnected charger

```
lucjan at cachyos ~ 20:22:36    
❯ upower -d
Device: /org/freedesktop/UPower/devices/line_power_AC
  native-path:          AC
  power supply:         yes
  updated:              czw, 20 lip 2023, 20:23:47 (4 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              no
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT0
  native-path:          BAT0
  vendor:               Hewlett-Packard
  model:                Primary
  serial:               02241 2018/03/22
  power supply:         yes
  updated:              czw, 20 lip 2023, 20:23:51 (0 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               discharging
    warning-level:       none
    energy:              29,355 Wh
    energy-empty:        0 Wh
    energy-full:         37,563 Wh
    energy-full-design:  46,512 Wh
    energy-rate:         0 W
    voltage:             11,753 V
    charge-cycles:       277
    percentage:          78%
    capacity:            80,7598%
    technology:          lithium-ion
    icon-name:          'battery-full-symbolic'

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              czw, 20 lip 2023, 20:23:49 (2 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               discharging
    warning-level:       none
    energy:              29,355 Wh
    energy-full:         37,563 Wh
    energy-rate:         0 W
    charge-cycles:       N/A
    percentage:          78%
    icon-name:          'battery-full-symbolic'

Daemon:
  daemon-version:  1.90.2
  on-battery:      yes
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: PowerOff
```
I'll check on other systems when I get back from vacation

**Comment by ghost** [comment]
My result (Fedora 38 Silverblue, 6.4.4-cbl, Lenovo Thinkpad L14)
https://www.diffchecker.com/lxJQTyhR/

**Comment by antuan1996** [comment]
The output of the command almost does not change after boot on 6.4.4-cbl on my laptop. The "state" value stays the same as the one during boot. There are not any new values in "history" section besides the one that was fetched on boot. 
I do get new values in this section on the LTS kernel, so the system knows the current state of the battery. 
```
$ upower -d
Device: /org/freedesktop/UPower/devices/line_power_ACAD
  native-path:          ACAD
  power supply:         yes
  updated:              Thu 20 Jul 2023 11:03:25 PM (28 seconds ago)
  has history:          no
  has statistics:       no
  line-power
    warning-level:       none
    online:              yes
    icon-name:          'ac-adapter-symbolic'

Device: /org/freedesktop/UPower/devices/battery_BAT1
  native-path:          BAT1
  vendor:               ASUS
  model:                A32-K55
  power supply:         yes
  updated:              Thu 20 Jul 2023 11:03:47 PM (6 seconds ago)
  has history:          yes
  has statistics:       yes
  battery
    present:             yes
    rechargeable:        yes
    state:               charging
    warning-level:       none
    energy:              47.6434 Wh
    energy-empty:        0 Wh
    energy-full:         71.148 Wh
    energy-full-design:  90.0055 Wh
    energy-rate:         58.1745 W
    voltage:             16.584 V
    charge-cycles:       N/A
    time to full:        24.2 minutes
    percentage:          66%
    capacity:            79.0485%
    technology:          lithium-ion
    icon-name:          'battery-full-charging-symbolic'
  History (charge):
    1689883427	66.000	charging
    1689883405	0.000	unknown
  History (rate):
    1689883427	58.174	charging
    1689883405	0.000	unknown

Device: /org/freedesktop/UPower/devices/DisplayDevice
  power supply:         yes
  updated:              Thu 20 Jul 2023 11:03:25 PM (28 seconds ago)
  has history:          no
  has statistics:       no
  battery
    present:             yes
    state:               charging
    warning-level:       none
    energy:              47.6434 Wh
    energy-full:         71.148 Wh
    energy-rate:         58.1745 W
    charge-cycles:       N/A
    time to full:        24.2 minutes
    percentage:          66%
    icon-name:          'battery-full-charging-symbolic'

Daemon:
  daemon-version:  0.99.20
  on-battery:      no
  lid-is-closed:   no
  lid-is-present:  yes
  critical-action: PowerOff

```

**Comment by andersrh** [comment]
Hi.
I have considered providing an LTS kernel which should solve the issue for you as far as I understand.

I'm gonna test it out and will let you know.

**Comment by andersrh** [comment]
There is now an LTS kernel available in the COPR repo.
You can try to see, if using this solves the issue.
If you have uksmd installed, then uninstall it and install uksmd-lts instead.

**Comment by antuan1996** [comment]
Thanks. The battery sensor works properly on the new LTS build from the COPR repo.  I will check other kernel builds tomorrow, I hope.

**Comment by antuan1996** [comment]
The issue is still presented on other variants of kernel in the COPR repo.
What patchset is used in the LTS builds?

**Comment by andersrh** [comment]
> The issue is still presented on other variants of kernel in the COPR repo. What patchset is used in the LTS builds?

We use all these patches which are in the 6.1 folder (not including subdirs) here: https://github.com/CachyOS/kernel-patches/tree/master/6.1

And then on top of that we include the BORE scheduler: https://github.com/CachyOS/kernel-patches/blob/master/6.1/sched/0001-bore-cachy.patch

And latency nice for CFS: https://github.com/CachyOS/kernel-patches/blob/master/6.1/misc/0001-Add-latency-priority-for-CFS-class.patch

**Comment by andersrh** [comment]
works with the LTS kernel.
